import Head from 'next/head'
import Main from './Main'

export default function Home() {
  return (
    <div >
      <Head>
        <title>App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9292423173741305"
          crossorigin="anonymous"></script>
      </Head>



      <Main />


    </div>
  )
}
